#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Part 2 conformer pool for O3.H2O (JOB-2026-0905-009).

14 initial structures, all charge 0 / singlet, built from the experimental
monomer geometries used in the Phase-1 baseline (run_baseline.ozone_geom /
water_geom) so that the pool is reproducible from a documented rule set.

Coverage:
  * H-bond donation from water to a TERMINAL ozone oxygen, along the in-plane
    lone-pair direction, along the O-O axis, and out of the ozone plane;
    near (H...O = 2.0 A) and far (2.9 A) contacts;
  * water rotating about its donating O-H axis (coplanar vs non-coplanar);
  * water O approaching the CENTRAL ozone oxygen (lone-pair contact above the
    plane, in-plane contact, and H-down bifurcated contact);
  * symmetric double donation across the two terminal oxygens;
  * side-on O_w contact with the terminal O...O edge, and a stacked
    (water plane parallel to the ozone plane) arrangement.

Atom order in every structure: O3 central, O3 terminal(+x), O3 terminal(-x),
water O, water H(donor/H1), water H(H2).

Writes inputs/o3_h2o_hydration/{c01..c14}.xyz and conformer_pool.json.
"""
import os
import json
import math
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IN_DIR = os.path.join(ROOT, 'inputs', 'o3_h2o_hydration')

R_OO = 1.2717          # ozone experimental r(O-O), Angstrom
ANG_OOO = 117.79       # ozone experimental angle
R_OH = 0.9584          # water experimental r(O-H)
ANG_HOH = 104.45       # water experimental angle
HALF_HOH = math.radians(ANG_HOH / 2.0)


def ozone_frame():
    """Central O at origin, terminal O at (+/-x, +y, 0); molecular plane = xy."""
    t = math.radians(ANG_OOO / 2.0)
    return np.array([[0.0, 0.0, 0.0],
                     [R_OO * math.sin(t), R_OO * math.cos(t), 0.0],
                     [-R_OO * math.sin(t), R_OO * math.cos(t), 0.0]])


def _unit(v):
    v = np.asarray(v, dtype=float)
    return v / np.linalg.norm(v)


def _rot_z(v, deg):
    a = math.radians(deg)
    c, s = math.cos(a), math.sin(a)
    return np.array([c * v[0] - s * v[1], s * v[0] + c * v[1], v[2]])


def _perp_basis(u, ref):
    u = _unit(u)
    ref = np.asarray(ref, dtype=float)
    e1 = ref - np.dot(ref, u) * u
    if np.linalg.norm(e1) < 1e-6:
        ref = np.array([1.0, 0.0, 0.0])
        if abs(u[0]) > 0.9:
            ref = np.array([0.0, 1.0, 0.0])
        e1 = ref - np.dot(ref, u) * u
    e1 = _unit(e1)
    e2 = np.cross(u, e1)
    return e1, e2


def _terminal_ext_inplane(frame, idx):
    """In-plane unit vector at a terminal oxygen that is perpendicular to its
    O-O bond and points to the OUTSIDE of the O3 framework (verified: no atom
    of the approach corridor is within 1.7 A of any ozone atom)."""
    bond = _unit(frame[0] - frame[idx])            # terminal O -> central O
    n = np.array([-bond[1], bond[0], 0.0])         # in-plane perpendicular
    probe = frame[idx] + 2.0 * n
    dmin = min(np.linalg.norm(probe - frame[i]) for i in range(3))
    if dmin < 1.9:                                 # pointing inside the V: flip it
        n = -n
    return _unit(n)


def dir_vector(name, frame):
    """Named approach directions resolved in the ozone frame.

    frame[0] = central O, frame[1] = terminal O (+x), frame[2] = terminal O (-x).
    All terminal-oxygen directions point to the exterior of the framework.
    """
    w_r = _unit(frame[1] - frame[0])          # central -> terminal(+x)
    z = np.array([0.0, 0.0, 1.0])
    mid23 = 0.5 * (frame[1] + frame[2])
    ext_r = _terminal_ext_inplane(frame, 1)   # exterior in-plane at terminal O(+x)
    ext_l = _terminal_ext_inplane(frame, 2)   # exterior in-plane at terminal O(-x)
    d = {
        # --- terminal O (+x, frame[1])
        'axis': w_r,                             # along the O-O bond extension (linear)
        'ext_inplane': ext_r,                    # in-plane, perpendicular, exterior
        'perp': z,                               # perpendicular to the ozone plane
        'perp_neg': -z,
        'tilt_up': _unit(ext_r + z),             # between in-plane-exterior and +z
        'tilt_down': _unit(ext_r - z),
        'tilt_axis': _unit(w_r + z),
        # --- terminal O (-x, frame[2]): mirror images
        'axis_L': _unit(frame[2] - frame[0]),
        'ext_inplane_L': ext_l,
        # --- central O / molecular centre
        'cent_out': _unit(mid23 - frame[0]),     # in-plane, central O -> O-O edge
        'cent_out_neg': -_unit(mid23 - frame[0]),  # in-plane, opposite (open) side
        'cent_z': z,
    }
    if name not in d:
        raise KeyError('unknown direction %r' % name)
    return d[name]


def place_h_donor(anchor, u, d, phi_deg, ref):
    """Water donates H1: H1 sits d (Angstrom) from the anchor along u, O_w lies
    further out on the same axis (linear O_w-H...O).  H2 is generated by the
    H-O-H angle and a rotation phi about the O_w->H1 axis."""
    u = _unit(u)
    h1 = np.asarray(anchor, dtype=float) + d * u
    ow = h1 + R_OH * u                    # O_w is beyond H1, away from the anchor
    e1, e2 = _perp_basis(u, ref)
    phi = math.radians(phi_deg)
    th = math.radians(ANG_HOH)
    v2 = math.cos(th) * (-u) + math.sin(th) * (math.cos(phi) * e1 + math.sin(phi) * e2)
    h2 = ow + R_OH * v2
    return np.array([ow, h1, h2])


def place_o_contact(anchor, u, d, b_vec, e_vec):
    """Water O sits d (Angstrom) from the anchor along u; the water bisector
    points along b_vec and the H-H axis along e_vec (orthogonalised vs b)."""
    u = _unit(u)
    ow = np.asarray(anchor, dtype=float) + d * u
    b = _unit(np.asarray(b_vec, dtype=float))
    e = np.asarray(e_vec, dtype=float)
    e = e - np.dot(e, b) * b
    if np.linalg.norm(e) < 1e-6:
        e = _perp_basis(b, [0.0, 0.0, 1.0])[0]
    e = _unit(e)
    h1 = ow + R_OH * (math.cos(HALF_HOH) * b + math.sin(HALF_HOH) * e)
    h2 = ow + R_OH * (math.cos(HALF_HOH) * b - math.sin(HALF_HOH) * e)
    return np.array([ow, h1, h2])


def resolve_anchor(anchor, frame):
    if isinstance(anchor, int):
        return frame[anchor], 'atom %d (%s)' % (
            anchor, 'central O' if anchor == 0 else 'terminal O')
    if anchor == 'mid23':
        return 0.5 * (frame[1] + frame[2]), 'midpoint of the two terminal O'
    if anchor == 'centroid':
        return frame.mean(axis=0), 'geometric centroid of O3'
    raise ValueError(anchor)


# ------------------------------------------------------------------ the pool
# mode 'h_donor': water donates H1 to the anchor oxygen, phi rotates H2 about
#                 the donating O-H axis, d = H1...O anchor distance.
# mode 'o_contact': the water OXYGEN contacts the anchor, d = O_w...anchor
#                 distance, b = bisector direction ('+u' / '-u' / '+x' / '+y'),
#                 e = H-H axis direction.
SPECS = [
    dict(id='c01', mode='h_donor', anchor=1, u='ext_inplane', d=2.00, phi=0.0,
         ref=[0, 0, 1], coverage='末端氧供氢键 / 面内外部方向 / 近接触',
         rule='H1 沿末端氧(+x)处"垂直键轴且指向分子外部"的面内方向接近，H1···O = 2.00 Å；'
              'O_w 在同一轴外侧；H2 绕 O_w–H1 轴旋转 0°（参考向量取 O3 平面法线）'),
    dict(id='c02', mode='h_donor', anchor=1, u='ext_inplane', d=2.00, phi=90.0,
         ref=[0, 0, 1], coverage='末端氧供氢键 / 面内外部方向 / 共面取向',
         rule='同 c01 的接近轴与距离；H2 绕 O_w–H1 轴旋转 90°（两个 H 均落在 O3 平面内）'),
    dict(id='c03', mode='h_donor', anchor=1, u='ext_inplane', d=2.90, phi=0.0,
         ref=[0, 0, 1], coverage='末端氧供氢键 / 面内外部方向 / 远接触',
         rule='同 c01 的接近方向；H1···O 放宽到 2.90 Å（远接触，检验是否收敛回近接触极小）'),
    dict(id='c04', mode='h_donor', anchor=1, u='axis', d=2.00, phi=0.0,
         ref=[0, 0, 1], coverage='末端氧供氢键 / 沿 O–O 键轴延长线（线性 O–O···H）',
         rule='H1 沿中心氧→末端氧键轴的延长线接近（线性 O–O···H–O），2.00 Å'),
    dict(id='c05', mode='h_donor', anchor=1, u='perp', d=2.00, phi=0.0,
         ref=[0, 1, 0], coverage='末端氧供氢键 / 垂直于 O3 平面（非共面）',
         rule='H1 沿 O3 平面法线 +z 从上方接近末端氧，2.00 Å；H2 绕轴 0°（参考向量取 +y）'),
    dict(id='c06', mode='h_donor', anchor=1, u='tilt_up', d=2.10, phi=60.0,
         ref=[0, 0, 1], coverage='末端氧供氢键 / 面内外部与垂直之间的倾斜方向',
         rule='H1 沿 (面内外部方向 + 平面法线) 归一化后的倾斜方向接近，2.10 Å；H2 旋转 60°'),
    dict(id='c07', mode='h_donor', anchor=0, u='cent_out_neg', d=2.10, phi=45.0,
         ref=[0, 0, 1], coverage='中心氧作受体 / 面内开放侧供氢键',
         rule='H1 沿中心氧背向两个末端氧的开放侧（面内 −y）接近，2.10 Å；H2 旋转 45°'
              '（中心氧为弱受体，用于检验是否收敛到末端氧型极小）'),
    dict(id='c08', mode='h_donor', anchor=2, u='ext_inplane_L', d=2.05, phi=30.0,
         ref=[0, 0, 1], coverage='另一侧末端氧供氢键（对称等效起点）',
         rule='与 c01 镜像：H1 沿末端氧(−x) 面内外部方向接近，2.05 Å；H2 旋转 30°'),
    dict(id='c09', mode='o_contact', anchor=0, u='cent_z', d=2.80, b='+u',
         e=[1, 0, 0], coverage='水氧接触中心氧 / 孤对朝向 O3（非共面）',
         rule='O_w 沿 +z 位于中心氧上方 2.80 Å；水分子对称轴沿 +u（H 朝上背离 O3，'
              '孤对电子端朝向中心氧）'),
    dict(id='c10', mode='o_contact', anchor=0, u='cent_out_neg', d=2.90, b='+u',
         e=[0, 0, 1], coverage='水氧接触中心氧 / 面内方向',
         rule='O_w 在 O3 平面内、背离两个末端氧的一侧，距中心氧 2.90 Å；对称轴沿 +u（H 朝外）'),
    dict(id='c11', mode='o_contact', anchor=0, u='cent_z', d=2.90, b='-u',
         e=[1, 0, 0], coverage='水氧接触中心氧 / 两个 H 朝向 O3（分叉型）',
         rule='O_w 位于中心氧上方 2.90 Å；对称轴沿 −u（两个 H 同时朝向中心氧，分叉双氢给体）'),
    dict(id='c12', mode='o_contact', anchor='mid23', u='perp', d=2.60, b='-u',
         e=[1, 0, 0], coverage='对称分叉双氢键（两个 H 分别指向两个末端氧）',
         rule='O_w 位于两个末端氧连线中点上方 2.60 Å；对称轴 −u（H 朝下），H–H 轴沿 O–O 边缘方向'),
    dict(id='c13', mode='o_contact', anchor='mid23', u='cent_out', d=3.00, b='+u',
         e=[0, 0, 1], coverage='侧向接触末端 O–O 边缘（面内，孤对朝向边缘）',
         rule='O_w 在 O3 平面内自两末端氧中点向外 3.00 Å；对称轴沿 +u（H 朝外，孤对朝向 O–O 边缘）'),
    dict(id='c14', mode='o_contact', anchor='centroid', u='perp', d=3.20, b='+x',
         e=[0, 1, 0], coverage='堆叠取向（水分子平面与 O3 平面平行）',
         rule='O_w 位于 O3 几何中心上方 3.20 Å；对称轴沿 +x、H–H 轴沿 +y（三者 z 相同，'
              '水分子平面与 O3 平面平行，堆叠）'),
]


def build(spec, frame=None):
    frame = ozone_frame() if frame is None else frame
    anchor, anchor_desc = resolve_anchor(spec['anchor'], frame)
    u = dir_vector(spec['u'], frame)
    if spec['mode'] == 'h_donor':
        water = place_h_donor(anchor, u, spec['d'], spec['phi'], spec['ref'])
    else:
        b = spec['b']
        if b == '+u':
            b_vec = u
        elif b == '-u':
            b_vec = -u
        elif b == '+x':
            b_vec = np.array([1.0, 0.0, 0.0])
        elif b == '+y':
            b_vec = np.array([0.0, 1.0, 0.0])
        else:
            b_vec = np.asarray(b, dtype=float)
        water = place_o_contact(anchor, u, spec['d'], b_vec, spec['e'])
    coords = np.vstack([frame, water])
    return coords


def write_xyz(path, coords):
    syms = ['O', 'O', 'O', 'O', 'H', 'H']
    lines = [str(len(syms)), 'O3-H2O initial conformer (Angstrom)']
    for s, c in zip(syms, coords):
        lines.append('%-2s %18.10f %18.10f %18.10f' % (s, c[0], c[1], c[2]))
    with open(path, 'w') as fh:
        fh.write('\n'.join(lines) + '\n')


def main():
    os.makedirs(IN_DIR, exist_ok=True)
    frame = ozone_frame()
    pool = []
    for spec in SPECS:
        coords = build(spec, frame)
        spec_out = dict(spec)
        spec_out['anchor_description'] = resolve_anchor(spec['anchor'], frame)[1]
        spec_out['u_vector'] = [round(float(x), 6) for x in dir_vector(spec['u'], frame)]
        spec_out['initial_coords_angstrom'] = [
            [round(float(x), 8) for x in row] for row in coords]
        pool.append(spec_out)
        write_xyz(os.path.join(IN_DIR, '%s.xyz' % spec['id']), coords)
    manifest = dict(
        job='JOB-2026-0905-009',
        purpose='O3.H2O initial conformer pool for the Phase-2A gas-phase search',
        n_conformers=len(pool),
        charge=0, multiplicity=1,
        atom_order='O3 central, O3 terminal(+x), O3 terminal(-x), water O, water H1, water H2',
        monomer_geometries=dict(
            ozone='experimental gas phase r(O-O)=%.4f A, angle=%.2f deg' % (R_OO, ANG_OOO),
            water='experimental gas phase r(O-H)=%.4f A, angle=%.2f deg' % (R_OH, ANG_HOH)),
        placement_rules=dict(
            h_donor='H1 placed d (A) from the anchor along u, O_w further out on the '
                    'same axis; H2 from the H-O-H angle and a rotation phi about O_w->H1',
            o_contact='water O placed d (A) from the anchor along u; bisector along b, '
                      'H-H axis along e (orthogonalised against b)'),
        conformers=pool)
    path = os.path.join(IN_DIR, 'conformer_pool.json')
    with open(path, 'w') as fh:
        json.dump(manifest, fh, indent=2)
    print('wrote %d conformers -> %s' % (len(pool), IN_DIR))
    print('manifest: %s' % path)


if __name__ == '__main__':
    main()
